
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author abhishek
 */
public class FirstChoices extends javax.swing.JFrame {

    /**
     * Creates new form FirstChoices
     */
    public FirstChoices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ABC_NEWS = new javax.swing.JButton();
        Financial_Times = new javax.swing.JButton();
        Al_ZAZEERA = new javax.swing.JButton();
        ARS_Techica = new javax.swing.JButton();
        Associates_Press = new javax.swing.JButton();
        BBC_news = new javax.swing.JButton();
        BBC_Sports = new javax.swing.JButton();
        Business_Insider = new javax.swing.JButton();
        CNBC = new javax.swing.JButton();
        ESPN_CRICINFO = new javax.swing.JButton();
        Entertainmet_weekly = new javax.swing.JButton();
        Fortune = new javax.swing.JButton();
        FOX_Sports = new javax.swing.JButton();
        Hacker_NEWS = new javax.swing.JButton();
        GoogleNEWS = new javax.swing.JButton();
        ESPN = new javax.swing.JButton();
        CNN = new javax.swing.JButton();
        ABC_NEWS17 = new javax.swing.JButton();
        Metro = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("All you need To Choose any single news source options");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        ABC_NEWS.setBackground(new java.awt.Color(255, 255, 255));
        ABC_NEWS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ABC_NEWS.setForeground(new java.awt.Color(0, 102, 255));
        ABC_NEWS.setText("ABC NEWS");
        ABC_NEWS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ABC_NEWSMouseEntered(evt);
            }
        });
        ABC_NEWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_NEWSActionPerformed(evt);
            }
        });

        Financial_Times.setBackground(new java.awt.Color(255, 255, 255));
        Financial_Times.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Financial_Times.setForeground(new java.awt.Color(0, 102, 255));
        Financial_Times.setText("Financial Times");
        Financial_Times.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Financial_TimesMouseEntered(evt);
            }
        });
        Financial_Times.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Financial_TimesActionPerformed(evt);
            }
        });

        Al_ZAZEERA.setBackground(new java.awt.Color(255, 255, 255));
        Al_ZAZEERA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Al_ZAZEERA.setForeground(new java.awt.Color(0, 102, 255));
        Al_ZAZEERA.setText("Al ZAZEERA");
        Al_ZAZEERA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Al_ZAZEERAMouseEntered(evt);
            }
        });
        Al_ZAZEERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Al_ZAZEERAActionPerformed(evt);
            }
        });

        ARS_Techica.setBackground(new java.awt.Color(255, 255, 255));
        ARS_Techica.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ARS_Techica.setForeground(new java.awt.Color(0, 102, 255));
        ARS_Techica.setText("ARS Technica");
        ARS_Techica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ARS_TechicaMouseEntered(evt);
            }
        });
        ARS_Techica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARS_TechicaActionPerformed(evt);
            }
        });

        Associates_Press.setBackground(new java.awt.Color(255, 255, 255));
        Associates_Press.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Associates_Press.setForeground(new java.awt.Color(0, 102, 255));
        Associates_Press.setText("Associates Press");
        Associates_Press.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Associates_PressMouseEntered(evt);
            }
        });
        Associates_Press.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Associates_PressActionPerformed(evt);
            }
        });

        BBC_news.setBackground(new java.awt.Color(255, 255, 255));
        BBC_news.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BBC_news.setForeground(new java.awt.Color(0, 102, 255));
        BBC_news.setText("BBC NEWS");
        BBC_news.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BBC_newsMouseEntered(evt);
            }
        });
        BBC_news.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBC_newsActionPerformed(evt);
            }
        });

        BBC_Sports.setBackground(new java.awt.Color(255, 255, 255));
        BBC_Sports.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        BBC_Sports.setForeground(new java.awt.Color(0, 102, 255));
        BBC_Sports.setText("BBC Sport");
        BBC_Sports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BBC_SportsMouseEntered(evt);
            }
        });
        BBC_Sports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BBC_SportsActionPerformed(evt);
            }
        });

        Business_Insider.setBackground(new java.awt.Color(255, 255, 255));
        Business_Insider.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Business_Insider.setForeground(new java.awt.Color(0, 102, 255));
        Business_Insider.setText("Business Insider");
        Business_Insider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Business_InsiderMouseEntered(evt);
            }
        });
        Business_Insider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Business_InsiderActionPerformed(evt);
            }
        });

        CNBC.setBackground(new java.awt.Color(255, 255, 255));
        CNBC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CNBC.setForeground(new java.awt.Color(0, 102, 255));
        CNBC.setText("CNBC");
        CNBC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CNBCMouseEntered(evt);
            }
        });
        CNBC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNBCActionPerformed(evt);
            }
        });

        ESPN_CRICINFO.setBackground(new java.awt.Color(255, 255, 255));
        ESPN_CRICINFO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ESPN_CRICINFO.setForeground(new java.awt.Color(0, 102, 255));
        ESPN_CRICINFO.setText("ESPN CRIC INFO");
        ESPN_CRICINFO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ESPN_CRICINFOMouseEntered(evt);
            }
        });
        ESPN_CRICINFO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESPN_CRICINFOActionPerformed(evt);
            }
        });

        Entertainmet_weekly.setBackground(new java.awt.Color(255, 255, 255));
        Entertainmet_weekly.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Entertainmet_weekly.setForeground(new java.awt.Color(0, 102, 255));
        Entertainmet_weekly.setText("Entertainment Weekly");
        Entertainmet_weekly.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Entertainmet_weeklyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Entertainmet_weeklyMouseExited(evt);
            }
        });
        Entertainmet_weekly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entertainmet_weeklyActionPerformed(evt);
            }
        });

        Fortune.setBackground(new java.awt.Color(255, 255, 255));
        Fortune.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Fortune.setForeground(new java.awt.Color(0, 102, 255));
        Fortune.setText("Fortune");
        Fortune.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FortuneMouseEntered(evt);
            }
        });
        Fortune.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FortuneActionPerformed(evt);
            }
        });

        FOX_Sports.setBackground(new java.awt.Color(255, 255, 255));
        FOX_Sports.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        FOX_Sports.setForeground(new java.awt.Color(0, 102, 255));
        FOX_Sports.setText("Fox Sports");
        FOX_Sports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                FOX_SportsMouseEntered(evt);
            }
        });
        FOX_Sports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FOX_SportsActionPerformed(evt);
            }
        });

        Hacker_NEWS.setBackground(new java.awt.Color(255, 255, 255));
        Hacker_NEWS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Hacker_NEWS.setForeground(new java.awt.Color(0, 102, 255));
        Hacker_NEWS.setText("Hacker News");
        Hacker_NEWS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Hacker_NEWSMouseEntered(evt);
            }
        });
        Hacker_NEWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hacker_NEWSActionPerformed(evt);
            }
        });

        GoogleNEWS.setBackground(new java.awt.Color(255, 255, 255));
        GoogleNEWS.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        GoogleNEWS.setForeground(new java.awt.Color(0, 102, 255));
        GoogleNEWS.setText("Google NEWS");
        GoogleNEWS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GoogleNEWSMouseEntered(evt);
            }
        });
        GoogleNEWS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoogleNEWSActionPerformed(evt);
            }
        });

        ESPN.setBackground(new java.awt.Color(255, 255, 255));
        ESPN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ESPN.setForeground(new java.awt.Color(0, 102, 255));
        ESPN.setText("ESPN");
        ESPN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ESPNMouseEntered(evt);
            }
        });
        ESPN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESPNActionPerformed(evt);
            }
        });

        CNN.setBackground(new java.awt.Color(255, 255, 255));
        CNN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CNN.setForeground(new java.awt.Color(0, 102, 255));
        CNN.setText("CNN");
        CNN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CNNMouseEntered(evt);
            }
        });
        CNN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNNActionPerformed(evt);
            }
        });

        ABC_NEWS17.setBackground(new java.awt.Color(255, 255, 255));
        ABC_NEWS17.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        ABC_NEWS17.setForeground(new java.awt.Color(255, 0, 51));
        ABC_NEWS17.setText("Not Find GO TO Next Choices");
        ABC_NEWS17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ABC_NEWS17MouseEntered(evt);
            }
        });
        ABC_NEWS17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ABC_NEWS17ActionPerformed(evt);
            }
        });

        Metro.setBackground(new java.awt.Color(255, 255, 255));
        Metro.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Metro.setForeground(new java.awt.Color(0, 102, 255));
        Metro.setText("METRO");
        Metro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MetroMouseEntered(evt);
            }
        });
        Metro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(GoogleNEWS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(44, 44, 44)
                            .addComponent(Hacker_NEWS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BBC_Sports, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ABC_NEWS, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Financial_Times)
                                .addGap(35, 35, 35)
                                .addComponent(Al_ZAZEERA, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(CNN, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Entertainmet_weekly, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(FOX_Sports, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Metro, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ABC_NEWS17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Associates_Press)
                            .addComponent(ARS_Techica)
                            .addComponent(ESPN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BBC_news)
                                    .addComponent(Business_Insider))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ESPN_CRICINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CNBC, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(66, 66, 66)
                        .addComponent(Fortune, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Al_ZAZEERA, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Financial_Times, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BBC_news, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Associates_Press, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BBC_Sports, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ABC_NEWS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ARS_Techica, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Business_Insider, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CNN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ESPN, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ESPN_CRICINFO, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Entertainmet_weekly, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(78, 78, 78)
                        .addComponent(ABC_NEWS17, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Fortune, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FOX_Sports, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CNBC, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(GoogleNEWS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hacker_NEWS, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Metro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
TextToSpeech tts;
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
tts=new TextToSpeech();
        tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("All you need to choose any single source and get trending news in that channel or newspaper",1.5f, false, false);
            f=new File(new File(".").getAbsolutePath().toString()+"\\tmpfile.txt");
    try{         fout=new FileOutputStream(f);
      dout=new DataOutputStream(fout);
        dout.writeBytes(null);}catch(Exception e){}
    }//GEN-LAST:event_formWindowOpened
File f;
FileOutputStream fout;
DataOutputStream dout;
    private void ABC_NEWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_NEWSActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=abc-news-au&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_NEWSActionPerformed
// https://newsapi.org/v1/articles?source=financial-times&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e
    private void Financial_TimesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Financial_TimesActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=financial-times&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_Financial_TimesActionPerformed

    private void Al_ZAZEERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Al_ZAZEERAActionPerformed
        // TODO add your handling code here:
    try {
            String s="https://newsapi.org/v1/articles?source=al-jazeera-english&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_Al_ZAZEERAActionPerformed

    private void ARS_TechicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARS_TechicaActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=ars-technica&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_ARS_TechicaActionPerformed

    private void Associates_PressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Associates_PressActionPerformed
    try {
            String s=" https://newsapi.org/v1/articles?source=associated-press&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_Associates_PressActionPerformed

    private void BBC_newsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBC_newsActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=bbc-news&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_BBC_newsActionPerformed

    private void BBC_SportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BBC_SportsActionPerformed
        // TODO add your handling code here:
    try {
            String s="https://newsapi.org/v1/articles?source=bbc-sport&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_BBC_SportsActionPerformed

    private void Business_InsiderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Business_InsiderActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=business-insider&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Business_InsiderActionPerformed

    private void CNBCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNBCActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=cnbc&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }       
    }//GEN-LAST:event_CNBCActionPerformed

    private void ESPN_CRICINFOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESPN_CRICINFOActionPerformed
           try {
            String s="https://newsapi.org/v1/articles?source=espn-cric-info&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
 // TODO add your handling code here:
    }//GEN-LAST:event_ESPN_CRICINFOActionPerformed

    private void Entertainmet_weeklyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entertainmet_weeklyActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=entertainment-weekly&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_Entertainmet_weeklyActionPerformed

    private void FortuneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FortuneActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=fortune&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        // TODO add your handling code here:
    }//GEN-LAST:event_FortuneActionPerformed

    private void FOX_SportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FOX_SportsActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=fox-sports&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_FOX_SportsActionPerformed

    private void Hacker_NEWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hacker_NEWSActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=hacker-news&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Hacker_NEWSActionPerformed

    private void GoogleNEWSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoogleNEWSActionPerformed
    try {
            String s=" https://newsapi.org/v1/articles?source=google-news&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_GoogleNEWSActionPerformed

    private void ESPNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESPNActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=espn&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_ESPNActionPerformed

    private void CNNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNNActionPerformed
    try {
            String s="https://newsapi.org/v1/articles?source=cnn&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_CNNActionPerformed

    private void ABC_NEWS17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ABC_NEWS17ActionPerformed
    this.dispose();
    new SecondChoices().show();// TODO add your handling code here:
    }//GEN-LAST:event_ABC_NEWS17ActionPerformed

    private void MetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetroActionPerformed
    try {
            String s=" https://newsapi.org/v1/articles?source=metro&sortBy=top&apiKey=5c21e514f48c4216a83d99bab827804e";
            dout.writeBytes(s);
            dout.close();fout.close();
            this.dispose();
            new MainPage().show();
        } catch (IOException ex) {
            Logger.getLogger(FirstChoices.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_MetroActionPerformed

    private void ABC_NEWSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABC_NEWSMouseEntered
    tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("A B C NEWS",1.5f, false, false);
    
    }//GEN-LAST:event_ABC_NEWSMouseEntered

    private void Financial_TimesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Financial_TimesMouseEntered
    tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Financial Times World",1.5f, false, false);
        // TODO add your handling code here:
    }//GEN-LAST:event_Financial_TimesMouseEntered

    private void ABC_NEWS17MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ABC_NEWS17MouseEntered
    tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Click for other Choices",1.5f, false, false);
        // TODO add your handling code here:
    }//GEN-LAST:event_ABC_NEWS17MouseEntered

    private void Al_ZAZEERAMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Al_ZAZEERAMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("AL ZAZEERA NEWS",1.5f, false, false);
       }//GEN-LAST:event_Al_ZAZEERAMouseEntered

    private void Associates_PressMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Associates_PressMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Associates Press news",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_Associates_PressMouseEntered

    private void BBC_newsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BBC_newsMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("BBC NEWS",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_BBC_newsMouseEntered

    private void BBC_SportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BBC_SportsMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("BBC Sports",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_BBC_SportsMouseEntered

    private void ARS_TechicaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ARS_TechicaMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("A R S Technica news",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_ARS_TechicaMouseEntered

    private void Business_InsiderMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Business_InsiderMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Business Insider News",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_Business_InsiderMouseEntered

    private void CNNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CNNMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("C N N News",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_CNNMouseEntered

    private void Entertainmet_weeklyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entertainmet_weeklyMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_Entertainmet_weeklyMouseExited

    private void Entertainmet_weeklyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Entertainmet_weeklyMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Entertainment Weekly news",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_Entertainmet_weeklyMouseEntered

    private void ESPNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ESPNMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("E S P N News",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_ESPNMouseEntered

    private void ESPN_CRICINFOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ESPN_CRICINFOMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("E S P N CRICKET INFO",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_ESPN_CRICINFOMouseEntered

    private void CNBCMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CNBCMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("C N B C",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_CNBCMouseEntered

    private void FortuneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FortuneMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Fortune",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_FortuneMouseEntered

    private void FOX_SportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FOX_SportsMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Fox Stars",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_FOX_SportsMouseEntered

    private void GoogleNEWSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoogleNEWSMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Google News",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_GoogleNEWSMouseEntered

    private void Hacker_NEWSMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Hacker_NEWSMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Hacker NEWS",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_Hacker_NEWSMouseEntered

    private void MetroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MetroMouseEntered
 tts.stopSpeaking();
 tts.setVoice("dfki-poppy-hsmm");
            tts.speak("Metro news",1.5f, false, false);
           // TODO add your handling code here:
    }//GEN-LAST:event_MetroMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstChoices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FirstChoices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ABC_NEWS;
    private javax.swing.JButton ABC_NEWS17;
    private javax.swing.JButton ARS_Techica;
    private javax.swing.JButton Al_ZAZEERA;
    private javax.swing.JButton Associates_Press;
    private javax.swing.JButton BBC_Sports;
    private javax.swing.JButton BBC_news;
    private javax.swing.JButton Business_Insider;
    private javax.swing.JButton CNBC;
    private javax.swing.JButton CNN;
    private javax.swing.JButton ESPN;
    private javax.swing.JButton ESPN_CRICINFO;
    private javax.swing.JButton Entertainmet_weekly;
    private javax.swing.JButton FOX_Sports;
    private javax.swing.JButton Financial_Times;
    private javax.swing.JButton Fortune;
    private javax.swing.JButton GoogleNEWS;
    private javax.swing.JButton Hacker_NEWS;
    private javax.swing.JButton Metro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
